require 'rubygems'
require 'nokogiri'
require 'open-uri'
require 'json'
require File.dirname(__FILE__) + '/../utils/utils'
require File.dirname(__FILE__) + '/../lib/ecommerce'
require File.dirname(__FILE__) + '/../lib/americanas'
require File.dirname(__FILE__) + '/../lib/extra'
require File.dirname(__FILE__) + '/../lib/ricardoeletro'
require File.dirname(__FILE__) + '/../lib/submarino'
require File.dirname(__FILE__) + '/../lib/miniinthebox'
